# Generated by Django 3.2.7 on 2021-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dates',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('workout_id', models.CharField(max_length=300)),
                ('user_id', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=10)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='exercises',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('workout_id', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=500)),
                ('reps', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='workouts',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
    ]
