# Generated by Django 3.2.7 on 2021-09-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dates',
            new_name='date',
        ),
        migrations.RenameModel(
            old_name='exercises',
            new_name='exercise',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
        migrations.RenameModel(
            old_name='workouts',
            new_name='workout',
        ),
    ]
