# Generated by Django 3.2.7 on 2021-09-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20210903_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exercise',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
