# Generated by Django 3.2.7 on 2021-09-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20210903_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='date',
        ),
    ]
