# Generated by Django 3.2.7 on 2021-09-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
            ],
        ),
    ]
